# Site settings
title: Электроника 101
description: "Электроника боюнча видеосабактар."
username: kalysosmonov
githubname: kalys
baseurl: ""
url: "http://e101.osmonov.com"

# Build settings
markdown: kramdown
permalink: pretty
