# Site settings
title: Электроника 1Ө1
description: "Электроника боюнча видеосабактар."
username: kalysosmonov
githubname: kalys
baseurl: ""
url: "http://elektronika101.com"

# Build settings
markdown: kramdown
permalink: pretty
